version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - hr-network
    depends_on:
      - backend   # 确保前端启动之前，后端已经启动

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - hr-network
    depends_on:
      - db   # 确保后端启动之前，数据库已经启动
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hr_system_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: mysql:5.7
    container_name: hr_system_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hr_system_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - hr-network
    volumes:
      - ./db-data:/var/lib/mysql

networks:
  hr-network:
    driver: bridge

volumes:
  db-data:
    driver: local
