version: '3.8'

services:
  frontend:
    build:
      context: . # 当前目录，包含Dockerfile
      dockerfile: Dockerfile # 前端的Dockerfile
    ports:
      - "8080:80"  # 映射前端容器的80端口到宿主机的8080端口
    networks:
      - hr-network

  backend:
    image: openjdk:11-jre-slim # 使用OpenJDK 11的官方镜像
    container_name: backend
    build:
      context: ./backend # 假设您的后端代码位于backend目录
    ports:
      - "8081:8080"  # 映射后端容器的8080端口到宿主机的8081端口
    networks:
      - hr-network
    environment:
      SPRING_PROFILES_ACTIVE: prod  # 根据需要设置Spring Boot环境变量

networks:
  hr-network:
    driver: bridge
