version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend  # 后端代码目录
      dockerfile: Dockerfile  # 后端 Dockerfile 路径
    container_name: springboot-backend
    ports:
      - "8080:8080"  # 映射端口到宿主机
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # 可根据需要设置环境变量

  # 前端服务
  frontend:
    build:
      context: ./frontend  # 前端代码目录
      dockerfile: Dockerfile  # 前端 Dockerfile 路径
    container_name: vue-frontend
    ports:
      - "8081:80"  # 映射端口到宿主机
    networks:
      - mynetwork
    depends_on:
      - backend  # 确保后端服务先启动

networks:
  mynetwork:
    driver: bridge  # 默认网络模式
